### ISSUE TITLE
Dashboard that shows all metrics

### ISSUE THREAD

**Issue by ghost** [kenhub/giraffe#72]
Hi,

I'm just getting started with Giraffee. Is there a simple way to make a dashboard that shows all metrics? I think it would help show which ones I have and how I can refine the dashboards from there.

Thanks!

-Teran

**Comment by gingerlime** [comment]
The Graphite built-in dashboard has some kind of an explorer feature to look at your data. Otherwise, I think [Grafana](https://grafana.com/) also has something similar.

Giraffe is much smaller and lighter-weight, for when you already know what you want to show on your dashboards, and is simpler to install and host (since it's just some HTML and JS, no server).

**Comment by ghost** [comment]
Okay, thank you! I appreciate it.
